// import aos, bootsrap, and icons later to design the page
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/sections/header";



const InitInter= Inter({ subsets: ["latin"] });

export const metadata = {
  title: "wish-watch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={InitInter.className }>
        <Header />
        {children}
      </body>
    </html>
  );
}
